"""
Copy an MLflow store into another one
=====================================
Used once, to move off the single-writer file store in mlruns/ onto Postgres +
object storage without losing the registered versions the scorer resolves.

The source is only ever read. Point --source at a server still serving the old
store (a throwaway container over a read-only mount is enough) and --dest at the
new one:

    docker run --rm -d --name mlflow-legacy -p 5002:5000 \\
      -v "$PWD/mlruns:/mlflow/mlruns:ro" -v "$PWD/mlartifacts:/mlflow/mlartifacts:ro" \\
      ghcr.io/mlflow/mlflow:v3.1.4 mlflow server --host 0.0.0.0 --port 5000 \\
      --backend-store-uri file:///mlflow/mlruns \\
      --artifacts-destination /mlflow/mlartifacts --serve-artifacts

    python scripts/migrate_mlflow_store.py --source http://localhost:5002 \\
                                           --dest http://localhost:5001

Run ids are NOT preserved -- the destination assigns its own. Version numbers
are, because versions are recreated in ascending order into an empty registry.
"""

import argparse
import sys
import tempfile
from pathlib import Path

import mlflow
import mlflow.artifacts
from mlflow.entities import Metric, Param, RunTag, ViewType
from mlflow.tracking import MlflowClient

PARAM_BATCH = 100
METRIC_BATCH = 1000
TAG_BATCH = 100

# Regenerated by the destination when the model is re-registered; copying it
# would point lineage at run ids that only exist in the source.
SKIP_TAG_PREFIXES = ("mlflow.log-model.history",)


def chunked(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def copy_experiments(src, dst):
    name_to_dest_id = {}
    for exp in src.search_experiments(view_type=ViewType.ALL):
        existing = dst.get_experiment_by_name(exp.name)
        if existing:
            dest_id = existing.experiment_id
        else:
            dest_id = dst.create_experiment(exp.name, tags=exp.tags or None)
        name_to_dest_id[exp.name] = dest_id
        print(f"  experiment {exp.name} -> {dest_id}")
    return name_to_dest_id


def copy_run(src, dst, src_run, dest_experiment_id):
    tags = [
        RunTag(k, v) for k, v in src_run.data.tags.items()
        if not k.startswith(SKIP_TAG_PREFIXES)
    ]
    dest_run = dst.create_run(
        experiment_id=dest_experiment_id,
        start_time=src_run.info.start_time,
        tags={t.key: t.value for t in tags},
    )
    dest_id = dest_run.info.run_id

    params = [Param(k, str(v)) for k, v in src_run.data.params.items()]
    for batch in chunked(params, PARAM_BATCH):
        dst.log_batch(dest_id, params=batch)

    # Full history, not the final value: the per-iteration eval curves are the
    # reason these runs are worth keeping at all.
    metrics = []
    for key in src_run.data.metrics:
        for m in src.get_metric_history(src_run.info.run_id, key):
            metrics.append(Metric(m.key, m.value, m.timestamp, m.step))
    for batch in chunked(metrics, METRIC_BATCH):
        dst.log_batch(dest_id, metrics=batch)

    # Guarded: asking the file-store artifact proxy for an empty run's artifact
    # root answers 500, not an empty listing.
    if src.list_artifacts(src_run.info.run_id):
        with tempfile.TemporaryDirectory() as tmp:
            local = Path(mlflow.artifacts.download_artifacts(
                run_id=src_run.info.run_id, tracking_uri=src.tracking_uri, dst_path=tmp
            ))
            dst.log_artifacts(dest_id, str(local))

    dst.set_terminated(dest_id, status=src_run.info.status,
                       end_time=src_run.info.end_time)
    return dest_id, len(params), len(metrics)


def copy_registered_models(src, dst, run_map, src_uri):
    for model in src.search_registered_models():
        try:
            dst.create_registered_model(model.name, description=model.description)
        except Exception:
            pass
        print(f"  model {model.name}")

        versions = sorted(src.search_model_versions(f"name='{model.name}'"),
                          key=lambda v: int(v.version))
        for v in versions:
            dest_run = run_map.get(v.run_id)
            if dest_run is None:
                sys.exit(f"    v{v.version} references run {v.run_id}, which was "
                         f"not copied. Migrate its experiment first.")

            # The model's own storage URI, not models:/name/version -- the
            # models: scheme is resolved by a registry client built from the
            # global tracking URI, which points at the destination here.
            download_uri = src.get_model_version_download_uri(model.name, v.version)
            with tempfile.TemporaryDirectory() as tmp:
                local = mlflow.artifacts.download_artifacts(
                    artifact_uri=download_uri, tracking_uri=src_uri, dst_path=tmp,
                )
                dst.log_artifacts(dest_run, local, artifact_path="model")

            created = dst.create_model_version(
                name=model.name,
                source=f"runs:/{dest_run}/model",
                run_id=dest_run,
                description=v.description,
                tags=v.tags or None,
            )
            if int(created.version) != int(v.version):
                sys.exit(f"    version drift: source v{v.version} landed as "
                         f"v{created.version}. Destination registry was not empty.")
            print(f"    v{created.version} <- run {dest_run}")

        for alias, version in (model.aliases or {}).items():
            dst.set_registered_model_alias(model.name, alias, version)
            print(f"    alias {alias} -> v{version}")


def main():
    p = argparse.ArgumentParser(description="Copy an MLflow store into another")
    p.add_argument("--source", required=True, help="Tracking URI to read from")
    p.add_argument("--dest", required=True, help="Tracking URI to write to")
    args = p.parse_args()

    # Writes go through the destination's artifact repo, which is resolved from
    # the global tracking URI rather than the client's. Reads from the source
    # pass tracking_uri= explicitly.
    mlflow.set_tracking_uri(args.dest)

    src = MlflowClient(tracking_uri=args.source)
    dst = MlflowClient(tracking_uri=args.dest)

    if dst.search_registered_models():
        sys.exit(f"{args.dest} already has registered models. Migrate into an "
                 f"empty registry, or version numbers will not line up.")

    print(f"Experiments  {args.source} -> {args.dest}")
    exp_ids = copy_experiments(src, dst)

    print("Runs")
    run_map, deleted = {}, []
    for name, dest_exp in exp_ids.items():
        src_exp = src.get_experiment_by_name(name)
        # ALL, not the default ACTIVE_ONLY: a soft-deleted run can still back a
        # registered version, and skipping it loses that version entirely.
        runs = src.search_runs([src_exp.experiment_id],
                               run_view_type=ViewType.ALL, max_results=50000)
        for run in sorted(runs, key=lambda r: r.info.start_time):
            dest_id, n_p, n_m = copy_run(src, dst, run, dest_exp)
            run_map[run.info.run_id] = dest_id
            if run.info.lifecycle_stage != "active":
                deleted.append(dest_id)
            print(f"  {run.info.run_id[:8]} -> {dest_id[:8]}  "
                  f"({n_p} params, {n_m} metric points)"
                  f"{'  [deleted]' if run.info.lifecycle_stage != 'active' else ''}")

    print("Registered models")
    copy_registered_models(src, dst, run_map, args.source)

    # Last, so the versions above could still be created from them.
    for dest_id in deleted:
        dst.delete_run(dest_id)

    print(f"\nCopied {len(run_map)} runs ({len(deleted)} re-deleted).")


if __name__ == "__main__":
    main()
